#!/bin/bash

################################################################################
# Instrument a gdb debug session capable of dumping vector registers.
#
# It has the target part in form of executing the target binary in proot
# environment, and gdb launch, which attaches to the GDB stub session exposed by
# QEMU.
#
# Example usage:
#   $ target-gdb binary-under-test with arguments
#
# Authors:
#   Marek Pikuła <m.pikula@partner.samsung.com>
################################################################################

GDB_PORT=1234
ROOT_DIR=/target

QEMU_ARGS="-g ${GDB_PORT}" "$(dirname "$0")/target-run" "$@" &

riscv64-unknown-linux-gnu-gdb \
    -ex "set sysroot ${ROOT_DIR}" \
    -ex "target remote :${GDB_PORT}"

fg 2> /dev/null
