#!/bin/bash

################################################################################
# Run a command in the target environment.
#
# It uses proot and QEMU to chroot to the target rootfs with option to enable
# GDB stub and set desired QEMU CPU configuration. If executed within the
# `target` directory, it translates the current working directory to be
# consistent in the target environment.
#
# By default it uses RVV-capable RISC-V CPU with VLEN=256. If you wish to use a
# different VLEN, set it as `RVV_VLEN` environment variable.
#
# Additional arguments for QEMU (like enabling GDB stub) can be passed by
# setting `QEMU_ARGS` environment variable.
#
# Example usage:
#   $ target-run binary with arguments
#
# Authors:
#   Marek Pikuła <m.pikula@partner.samsung.com>
################################################################################

set -e

RVV_VLEN=${RVV_VLEN:-256}
TARGET_DIR=/target

# If executing in the `target` directory, translate the current work directory
# to the directory within the Docker environment.
if [[ $PWD/ = ${TARGET_DIR}/* ]]; then WORK_DIR="${PWD//${TARGET_DIR}/}/"; fi

proot \
    -q "qemu-riscv64 -cpu rv64,v=false ${QEMU_ARGS}" \
    ${WORK_DIR:+-w ${WORK_DIR}} \
    -R "${TARGET_DIR}" \
    "${@:-${SHELL}}"
